name: eeg2025
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - mne
  - tqdm
  - pytorch
  - pytorch-cuda=12.1
  - pip:
      - braindecode>=0.7
      - eegdash
